# Generated by Django 2.0.6 on 2019-11-10 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsterName', models.CharField(max_length=150)),
                ('monsterAttack', models.IntegerField()),
                ('monsterHealth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('userAttack', models.IntegerField()),
                ('userHealth', models.IntegerField()),
                ('itemEquipped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaponName', models.CharField(max_length=100, unique=True)),
                ('weaponAttack', models.IntegerField()),
                ('weaponForeignKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameApp.UserModel')),
            ],
        ),
        migrations.AddField(
            model_name='monstermodel',
            name='monsterForeignKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameApp.UserModel'),
        ),
    ]
