# Generated by Django 2.0.6 on 2019-11-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='itemEquipped',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='userAttack',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='userHealth',
        ),
    ]
