# Generated by Django 2.0.6 on 2019-11-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0002_auto_20191110_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='itemEquipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='userAttack',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='userHealth',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='monstermodel',
            name='monsterAttack',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monstermodel',
            name='monsterHealth',
            field=models.IntegerField(default=100),
        ),
    ]
