# Generated by Django 2.0.6 on 2019-11-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0005_auto_20191111_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userAttack',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userHealth',
            field=models.IntegerField(default=0),
        ),
    ]
