# Generated by Django 2.0.6 on 2019-11-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0007_auto_20191111_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userAttack',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userHealth',
            field=models.IntegerField(default=108),
        ),
    ]
