# Generated by Django 2.0.6 on 2019-11-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0012_auto_20191112_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monstermodel',
            name='monsterAvatar',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userAttack',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userAvatar',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userHealth',
            field=models.IntegerField(default=254),
        ),
        migrations.AlterField(
            model_name='weaponmodel',
            name='weaponAvatar',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
