# Generated by Django 3.0.3 on 2020-02-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0013_auto_20191112_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userAttack',
            field=models.IntegerField(default=17),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userHealth',
            field=models.IntegerField(default=196),
        ),
    ]
